WIP:  #109 - Create Driver Application
diglit/volunteer-toronto-volunteer-drivers-app pull request #110
Opened 2021-04-03 23:49 UTC by ynynl

#109

2021-04-03 23:52 UTC, l2silver commented on web-client/package.json
> +    "@material-ui/data-grid": "*",
This looks a bit problematic. you always want to version control so that if the library is updated, we won't necessarily use is it if it's a breaking update.

2021-04-03 23:55 UTC, l2silver commented on web-client/src/shared/redux/driverApplications/index.ts
> +        approved: false,
Do we need a rejected state also?

2021-04-03 23:56 UTC, l2silver commented on web-client/src/shared/components/driver-applications/ApplicationList/index.tsx
>          <>
How come you're wrapping this in a react fragment?

2021-04-03 23:57 UTC, l2silver commented on web-client/src/shared/components/driver-applications/ApplicationList/index.tsx
Really clean page of code. it looks beautiful

2021-04-03 23:59 UTC, l2silver requested changes
So, do we need a rejected state? If we don't, then I think this is looking really strong. Or maybe we can add it in at a later time with another ticket?

2021-04-04 00:01 UTC, ynynl commented on web-client/src/shared/redux/driverApplications/index.ts
> +        approved: false,
yesss, adding reject will make more sense.

2021-04-04 00:17 UTC, l2silver commented on web-client/package.json
> -    "@material-ui/data-grid": "*",
We still need data-grid, we just need a specific version: ^4.0.0-alpha.24 could work, or whatever version you're currently using.

2021-04-04 00:19 UTC, l2silver reviewed
Oh yeah that's better. So how are we from this being done? Is it still a WIP?

2021-04-04 00:25 UTC, ynynl commented
> Oh yeah that's better. So how are we from this being done? Is it still a WIP?

I need to implement the reject/approve handlers, and wait for Wendy to complete the Review component and see how to use it here.

2021-04-06 03:23 UTC, l2silver commented on web-client/src/shared/components/driver-applications/ApplicationList/index.tsx
> +        setRowsPerPage(+event.target.value);
What is the + doing here?

2021-04-06 03:25 UTC, l2silver commented on web-client/src/shared/components/driver-applications/ApplicationReview/index.tsx
> +        const newState = applicationList.map(s => (s.id === id) ? { ...s, rejected: false, approved: true } : s)
very clean!

2021-04-06 03:27 UTC, l2silver commented on web-client/src/shared/components/driver-applications/ApplicationReview/index.tsx
> +import React, { ChangeEvent, useState } from 'react';
So for approving, rejecting, and adding comments, are posting those change to the api somewhere?

2021-04-06 03:29 UTC, ynynl commented on web-client/src/pages/api/applications/index.ts
> +}
I try to learn fetching Api and redux thunk as well so I built this mock.

2021-04-06 03:30 UTC, l2silver commented on web-client/src/shared/services/application.tsx
> +        method: 'POST',
I know this doesn't really matter because this is a mock call, but for REST when you're retrieving data without manipulating anything in a database, it's best to used GET.

2021-04-06 03:30 UTC, ynynl commented on web-client/src/shared/components/driver-applications/ApplicationList/index.tsx
> +                                                <Button variant="outlined" color="primary">Review Application</Button>
The 'review application' button links to the path with id to identify the right application

2021-04-06 03:31 UTC, l2silver commented on web-client/src/shared/services/application.tsx
> +
I think I would love to see some service calls for approving and rejecting the applications here as well, if it's possible. But this ticket is getting quite big, so it might make sense to add that work to another ticket.

2021-04-06 03:32 UTC, l2silver commented on web-client/src/shared/redux/driverApplications/index.ts
> +// export const fetchApplications = async () => {
What's going on here?

2021-04-06 03:32 UTC, l2silver commented on web-client/src/shared/redux/driverApplications/index.ts
> +    extraReducers:
Excellent research. I've never used the extra reducers myself, but it looks good.

2021-04-06 03:33 UTC, l2silver requested changes
Hey @ynynl , looking really good. I left a few comments, but I think we're almost done with this one! Amazing!

2021-04-06 03:37 UTC, ynynl commented on web-client/src/shared/components/driver-applications/ApplicationReview/index.tsx
> +import React, { ChangeEvent, useState } from 'react';
Not yet. I am looking for a way to write in the mock api data so I can test it. Currently it only allows read.

2021-04-06 03:38 UTC, ynynl commented on web-client/src/shared/components/driver-applications/ApplicationList/index.tsx
> +        setRowsPerPage(+event.target.value);
It's for the MUI pagination

2021-04-06 03:40 UTC, ynynl commented on web-client/src/shared/services/application.tsx
> +
Thank you for reviewing the code! I will make another ticket for it.

2021-04-08 01:08 UTC, l2silver approved these changes

2021-04-08 01:11 UTC, l2silver commented on web-client/src/shared/components/driver-applications/ApplicationList/index.tsx
> +        setRowsPerPage(+event.target.value);
Ah, it converts the string to a number! Brilliant

2021-04-08 01:13 UTC, l2silver commented on web-client/src/pages/api/applications/index.ts
> +}
awesome

2021-04-08 01:15 UTC, l2silver commented on web-client/src/shared/services/application.tsx
> +
Thanks

2021-04-08 01:15 UTC, l2silver approved these changes
Thanks Yinyin! Perfect

2021-04-08 01:15 UTC, merged