cypress pre-tests for Organizations tab
diglit/volunteer-toronto-volunteer-drivers-app pull request #114
Opened 2021-04-05 16:27 UTC by swatiDgithub

Hello, Should I comment all the code ?

2021-04-05 19:42 UTC, l2silver commented
> Hello, Should I comment all the code ?

Yeah, @swatiDgithub anything that's causing a failing test you should comment out with a #TODO comment saying to add it back in when the code for it is written

2021-04-08 00:55 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/orgnizationsTab.spec.js
> +        cy.type(input)
Will this work? I think that you mind need to chain this to the line before (.clear().type())

2021-04-08 01:02 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/orgnizationsTab.spec.js
> +        cy.contains(input, { timeout: 500})
So I think for this to work, what we're looking for is a row in a table with the correct user, and no other users. So we'll need to confirm that certain rows are hidden, and the correct rows are being shown. 

I believe you can use findByRole('table') to find the table, and then findByText within to find
`
const resultsTable =  cy.findByRole('table')
const correctRow = resultsTable.findByText('firstName lastName')
`

2021-04-08 01:03 UTC, l2silver commented on e2e/cypress/support/commands.js
>  import '@testing-library/cypress/add-commands';
Very nice!

2021-04-08 01:07 UTC, l2silver requested changes
I've left a few comments, but I also had another idea. 

Instead of commenting out the code, lets use ignoreTestFiles (https://docs.cypress.io/guides/references/configuration#Folders-Files) to ignore your new tests, and then we'll remove them as soon as the code is written for them.

2021-04-08 03:25 UTC, swatiDgithub commented
Thanks Leigh. Please see latest changes. I added ignoreTestFiles, However it was not ignoring the test in my local. Will try changing the code if does not pass in build.

2021-04-08 22:15 UTC, swatiDgithub commented
There are 2 tickets and they seem duplicate for cypress tests for Organizations Tab. 
#114 
#107 
I have referred to this feature as feature/107. Please suggest

2021-04-09 00:03 UTC, l2silver approved these changes
I've left a few comments, but I also had another idea. 

Instead of commenting out the code, lets use ignoreTestFiles (https://docs.cypress.io/guides/references/configuration#Folders-Files) to ignore your new tests, and then we'll remove them as soon as the code is written for them.

2021-04-09 00:03 UTC, merged