#85 - Create user management table
diglit/volunteer-toronto-volunteer-drivers-app pull request #120
Opened 2021-04-09 20:55 UTC by Haris188

2021-04-10 01:00 UTC, l2silver commented on web-client/src/shared/components/organization/members/Table.tsx
> +            : <Typography>No Member to show</Typography>
Not sure about p tag in a table. Do you think we could either put this inside a cell, or move it out of the table somehow?

Thanks.

2021-04-10 01:01 UTC, l2silver commented on web-client/src/shared/redux/organization/members/index.ts
> +import {
i love how clean and simple this all is. Great work

2021-04-10 01:03 UTC, l2silver requested changes
Awesome work, just one little change. Thanks!

2021-04-10 18:54 UTC, Haris188 commented on web-client/src/shared/components/organization/members/Table.tsx
> +            : <Typography>No Member to show</Typography>
Yes!

2021-04-12 21:15 UTC, Haris188 commented
@l2silver  Is this good now?

2021-04-21 01:05 UTC, l2silver approved these changes

2021-04-21 01:05 UTC, merged