Feature/81
diglit/volunteer-toronto-volunteer-drivers-app pull request #121
Opened 2021-04-10 01:56 UTC by caymanh

1. installed react-modal to simulate popup card since the component has not been created
2. added an "Email" button on /driver-search as a placeholder for the email icon which has not been added to the page
3. imported useState to /drive-search for handling the display and hiding of the popup
4. added functionality to display popup when users click on the "Email" button
5. added functionality to close the popup when users click on either the "Close" button in the card or outside the Card area

2021-04-10 15:36 UTC, ynynl commented on web-client/package.json
> +    "react-modal": "^3.12.1",
Hey @caymanh, I think you can use Material UI for popup https://material-ui.com/components/dialogs/

2021-04-11 13:09 UTC, caymanh commented on web-client/package.json
> +    "react-modal": "^3.12.1",
hi @ynynl, thanks for your feedback! I have uninstalled the react-modal package and used Material UI to create a placeholder popup component instead. let me know if you have any other comments.

2021-04-21 01:07 UTC, l2silver commented on web-client/src/shared/components/drivers-search/List/DriverCard/index.tsx
> +        <button onClick = {() => setOpenPopup(true)}>Email</button>
Do you think you could use material ui components where possible, like for the button

2021-04-21 01:13 UTC, l2silver requested changes
So, I've added a couple of comments. Looks like we need to make sure the popup content matches the designs. And I need you to change the name Popup to something more specific to this particular component. Something like MessagingPopup , and change it everywhere that is appropriate. Thanks @caymanh  great work!

2021-04-21 01:13 UTC, l2silver commented on web-client/src/shared/components/drivers-search/Popup/index.tsx
> +                <div>Placeholder for Title</div>
Looks like the details of the popup are a little off. We need all the information included in the design spec for this ticket.

2021-04-21 16:05 UTC, caymanh commented on web-client/src/shared/components/drivers-search/List/DriverCard/index.tsx
> +        <button onClick = {() => setOpenPopup(true)}>Email</button>
@l2silver thanks for your feedback! yes, I can replace the button with material UI component

2021-04-21 16:08 UTC, caymanh commented on web-client/src/shared/components/drivers-search/Popup/index.tsx
> +                <div>Placeholder for Title</div>
@l2silver noted. I will rename the Popup component to MessagingPopup. Regarding your comment on the details of the popup - the reason why I did not fully build out the popup according to the design spec was that I thought that the popup card itself is a separate ticket (#83) and hence, I merely used a placeholder for now while waiting for that ticket to be assigned and completed before I replaced the current placeholder with the actual card. however, I'm happy to build out the actual card as per ticket #83 if that works better for you.

2021-04-22 13:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=121) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=121) it.</sub>

2021-04-23 01:13 UTC, l2silver commented on web-client/src/shared/components/drivers-search/Popup/index.tsx
> +                <div>Placeholder for Title</div>
Omg @caymanh you're absolutely right! Sorry about that. The placeholder is perfect!

2021-05-01 18:36 UTC, merged