Feature/sub217
diglit/volunteer-toronto-volunteer-drivers-app pull request #224
Opened 2021-05-17 08:12 UTC by Haris188

2021-05-17 08:24 UTC, Haris188 commented
@ynynl @l2silver, Code might look repetitive but in long run its not.

2021-05-18 03:40 UTC, l2silver commented on web-client/src/pages/organization/member/[route].tsx
> +        {slug: 'drivers-search', label:'Driver Pre-Screen', component: <DriversSearch />}
I really like how you set this up! Comes together very easily.

2021-05-18 03:54 UTC, l2silver requested changes
Amazing work! I can't believe you put this altogether.

2021-05-18 03:54 UTC, l2silver commented on web-client/src/pages/volunteer-toronto/member/[route].tsx
> +        {slug: 'drivers-search', label:'Driver Pre-Screen', component: <DriversSearch />}
Can we give volunteer-toronto members the organization tab too? Thanks

2021-05-18 03:54 UTC, l2silver commented on web-client/src/shared/components/layout/LoadingRouter/index.tsx
> +import React, {useEffect} from 'react'
So what does this do exactly?

2021-05-18 03:54 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +  domain:string
can we change domain to organization?

2021-05-18 03:54 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +    return `/${domain ==='vt' ? 'volunteer-toronto': domain === 'org' ? 'organization' : 'individual'}/${role}`
Ah sorry, there is no individual space, that's just supposed to be the organization staff role

So there's 4 dashboards.
vt/admin
vt/member
organization/admin
organization/member

2021-05-18 16:44 UTC, Haris188 commented on web-client/src/pages/volunteer-toronto/member/[route].tsx
> +        {slug: 'drivers-search', label:'Driver Pre-Screen', component: <DriversSearch />}
Yes Leigh. But there is no organization component built. So should I just make a tab and leave it empty?

2021-05-18 16:45 UTC, Haris188 commented on web-client/src/shared/components/layout/LoadingRouter/index.tsx
> +import React, {useEffect} from 'react'
This basically redirects calls from /vt/admin, /vt/member, /org/admin, /org/member to driver-search tab

2021-05-18 16:51 UTC, Haris188 commented on web-client/src/shared/components/SignInPage/index.tsx
> +    return `/${domain ==='vt' ? 'volunteer-toronto': domain === 'org' ? 'organization' : 'individual'}/${role}`
So which page would a organization staff role login lands on?

2021-05-18 16:56 UTC, Haris188 commented on web-client/src/shared/components/SignInPage/index.tsx
> +    return `/${domain ==='vt' ? 'volunteer-toronto': domain === 'org' ? 'organization' : 'individual'}/${role}`
@l2silver Thanks for the review and appreciation!

2021-05-19 01:48 UTC, l2silver commented on web-client/src/pages/volunteer-toronto/member/[route].tsx
> +        {slug: 'drivers-search', label:'Driver Pre-Screen', component: <DriversSearch />}
Yep!

2021-05-19 01:49 UTC, l2silver commented on web-client/src/shared/components/layout/LoadingRouter/index.tsx
> +import React, {useEffect} from 'react'
excellent

2021-05-19 01:49 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +    return `/${domain ==='vt' ? 'volunteer-toronto': domain === 'org' ? 'organization' : 'individual'}/${role}`
Lets have all the pages start on driver-search

2021-05-19 02:14 UTC, Haris188 commented on web-client/src/shared/components/SignInPage/index.tsx
> +    return `/${domain ==='vt' ? 'volunteer-toronto': domain === 'org' ? 'organization' : 'individual'}/${role}`
So, It would be localhost/driver-search for individual login?

2021-05-19 04:28 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +    return `/${domain ==='vt' ? 'volunteer-toronto': domain === 'org' ? 'organization' : 'individual'}/${role}`
the individual login is organization/member/driver-search

2021-05-21 23:43 UTC, l2silver approved these changes

2021-05-21 23:44 UTC, merged