Feature/207
diglit/volunteer-toronto-volunteer-drivers-app pull request #232
Opened 2021-05-23 04:58 UTC by ynynl

#207

2021-05-23 12:08 UTC, l2silver commented on web-client/src/shared/components/volunteer-toronto/organizations/CreateNew/CreateNewDialogs.tsx
> +         * TODO:
Perfect!

2021-05-23 12:16 UTC, l2silver approved these changes
Excellent!

2021-05-23 12:16 UTC, l2silver commented on web-client/src/shared/components/volunteer-toronto/organizations/CreateNew/CreateNewDialogs.tsx
> +        profile: string | FileList,
so profile is the image?

2021-05-23 12:17 UTC, l2silver requested changes
Oh I just realized, the accompanying cypress tests are failing (This is a new thing we're trying out). Do you think you could get those tests to pass?

2021-05-25 01:21 UTC, ynynl commented
> Oh I just realized, the accompanying cypress tests are failing (This is a new thing we're trying out). Do you think you could get those tests to pass?

I ran the cypress test on my local but the test failed at the logging page. The credentials 'admin@diglit.com','Password@123' for the sign in page didn't work, and the test was stuck in this step, so I didn't make the test running on my page.

Another issue is the cypress looks for the 'Create Org' button in the VT member tab. In the ticket description #205 you said the button is actually in the Organization tab instead of VT member tab as in the xd file, right?

2021-05-25 01:22 UTC, ynynl commented
> Oh I just realized, the accompanying cypress tests are failing (This is a new thing we're trying out). Do you think you could get those tests to pass?

I ran the cypress test on my local but the test failed at the logging page. The credentials 'admin@diglit.com','Password@123' for the sign in page didn't work, and the test was stuck in this step, so I didn't make the test running on my page.

Another issue is in the ticket description  #205 you said the 'Create Org' button is actually in the Organization tab instead of VT member tab as in the xd file, while the cypress still looks for the button in the VT member tab.  I think we should make

2021-05-25 12:36 UTC, l2silver commented
> > Oh I just realized, the accompanying cypress tests are failing (This is a new thing we're trying out). Do you think you could get those tests to pass?
> 
> I ran the cypress test on my local but the test failed at the logging page. The credentials '[admin@diglit.com](mailto:admin@diglit.com)','Password@123' for the sign in page didn't work, and the test was stuck in this step, so I didn't make the test running on my page.
> 
> Another issue is the cypress looks for the 'Create Org' button in the VT member tab. In the ticket description #205 you said the button is actually in the Organization tab instead of VT member tab as in the xd file, right?

@ynynl Interesting. I'll take a look at the login issue, but what I would like going forward is that the developer make sure the cypress tests pass. Feel free to change the tests so that they work, like for example, looking for a button that shouldn't be there. Because it's easier for the developers to change the tests than for the tester to change the code.

2021-05-27 04:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=232) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ynynl<br/>:x: Leigh Silverstein<br/><hr/>**Leigh Silverstein** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=232) it.</sub>

2021-05-27 04:48 UTC, l2silver commented
Hey @swatiDgithub @ynynl 

So I tried to fix some of the errors. I left a few for @ynynl to fix up, but I wanted to point you both to my commit: https://github.com/diglit/volunteer-toronto-volunteer-drivers-app/pull/232/commits/79a3365b8f2f8d15adfee7370ff2c232de17bbd9

Take a look at it and notice some of the issues we ran into. Looks like gherkin cypress plugin works a little bit differently than the traditional syntax.

One of the errors that still exists is that the user doesn't have a way of clicking to close the popup. We should definitely have one, even though the designs were missing it.

2021-05-28 02:16 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg.feature
> +            Given User is in Organizations Tab
@swatiDgithub 
I needed to make sure the user was in the right tab. I forgot to tell you, I changed the create org tab to occur in the organizations page as opposed to the members tab

2021-05-28 02:17 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg.feature
> +  And User enters "<OrgName>","<accManagerName>","<accManagerEmail>" and "<accManagerPwd>" on the Create Org Popup
@swatiDgithub Looks like for our cypress cucumber plugin, this correct format for variables is "<something>". Who knew?

2021-05-28 02:18 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg.feature
> +  When User clicks on Create Organization button on Popup
@swatiDgithub This was missing an accompanying step. This is really hard to pick up . I'm going to be on the look out for tools to help with these kinds of errors

2021-05-28 02:19 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +// this file is implementation for createOrg.Feature file.
@swatiDgithub 
One of the things I decided to do after looking through a bit of code was change the file organization for step files. Instead of putting them in a communal directory, we're going to keep things very close to the actual feature file.

basically where ever the feature file is, we create a folder with the same name as the feature, and add our step files which should be named .step.js

2021-05-28 02:20 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +Before(() => {
This was also a bit of an issue. You used the cy.before syntax here, but I think we need to use the cucumber syntax in these step files

2021-05-28 02:20 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +Before(() => {
@swatiDgithub ^^

2021-05-28 02:21 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +  if(OrgName) cy.findByLabelText('Organization Name').type(OrgName)
I really like using the findByLabelText because it's very descriptive and it's a good check for accessibility to.

2021-05-28 02:21 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +  if(OrgName) cy.findByLabelText('Organization Name').type(OrgName)
@swatiDgithub ^^

2021-05-28 02:22 UTC, l2silver commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +// TODO-BACKEND need to wait for backend to be up and running to confirm that this is working properly
@swatiDgithub 

So this one we're just not ready for yet without the backend. I'll add it back in once we get the backend rolling

2021-05-28 02:24 UTC, l2silver commented on e2e/cypress/support/commands.js
> +    cy.findByText(/Welcome back/i)
@swatiDgithub This one is kind of interesting. Sometimes cypress needs to look for specific landmarks to know that the page has loaded properly. It's a bit of an art figuring this one out.

2021-05-28 02:24 UTC, l2silver commented on web-client/src/pages/api/sessions/create.ts
> +},
@ynynl This was how I added the user to the mock session create api

2021-05-28 02:26 UTC, l2silver commented on web-client/src/shared/components/volunteer-toronto/organizations/CreateNew/CreateNewDialogs.tsx
> +                                id="accountManager"
@ynynl Very small issue, I had to add id to a lot of the textfields. Without the id, the label doesn't associate properly with the text input (This is mostly bad for accessibility reasons, as screen readers won't beable to understand which labels are connected to which textfields.)

2021-05-28 13:55 UTC, swatiDgithub commented on e2e/cypress/integration/volunteerTorontoUser/createOrg.feature
> +            Given User is in Organizations Tab
Got it. Will make a note for next use cases.

2021-05-28 13:55 UTC, swatiDgithub commented on e2e/cypress/integration/volunteerTorontoUser/createOrg.feature
> +  And User enters "<OrgName>","<accManagerName>","<accManagerEmail>" and "<accManagerPwd>" on the Create Org Popup
hmm! Okay. Somehow the tests were not picking up the parameters when entered in "". But will be using this format going forward.

2021-05-28 13:56 UTC, swatiDgithub commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +// this file is implementation for createOrg.Feature file.
Noted.

2021-05-28 14:23 UTC, swatiDgithub commented on e2e/cypress/integration/volunteerTorontoUser/createOrg.feature
> +  When User clicks on Create Organization button on Popup
Not sure if I understand which step was missing. you mean 'When User clicks on Create Organization button on Popup step was missing ?  Line 11 step is the same as that ,though I have not mentioned 'on popup' in the step description.

2021-05-28 14:42 UTC, swatiDgithub commented on e2e/cypress/integration/volunteerTorontoUser/createOrg/index.steps.js
> +  if(OrgName) cy.findByLabelText('Organization Name').type(OrgName)
Noted.

2021-05-30 00:56 UTC, ynynl commented
All of the cypress tests passed on my local, I am not sure what happened in the Travis check. It seems the login page sometimes is broken. 
@l2silver

2021-05-30 01:22 UTC, l2silver commented
> All of the cypress tests passed on my local, I am not sure what happened in the Travis check. It seems the login page sometimes is broken.
> @l2silver

I'll take a look!

2021-06-01 04:54 UTC, l2silver commented
Hey @Haris188 , @ynynl is having a bit of trouble with getting the last cypress tests to pass. Do you think you could try and figure out what's wrong?

2021-06-06 21:02 UTC, closed without merging