Feature/181 Create endpoints for /users
diglit/volunteer-toronto-volunteer-drivers-app pull request #244
Opened 2021-05-29 23:11 UTC by cemgurbey

###  Hierarchy levels (lowest to highest):
* Driver
* OrgMember
* OrgAdmin
* VTOMember
* VTOAdmin

 I used [this part of the Django documentation](https://docs.djangoproject.com/en/3.2/topics/auth/default/#proxy-models) to create proxy permissions for each user type to apply CRUD operations hierarchically. Later, I simply used [DRF's custom permissions](https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions) to make the endpoint views.

###  Created Endpoints:
* POST http://0.0.0.0:8000/users/api/driver/create/ (Creates a Driver user, can be seen by anyone)
* GET http://0.0.0.0:8000/users/api/drivers/ (Lists all the drivers in the database, can be seen by anyone)
* PUT http://0.0.0.0:8000//users/api/driver/<pk>/  (Displays individual driver, where **pk** is the primary key of the driver, e.g. http://0.0.0.0:8000//users/api/driver/1/  , can be edited/deleted by higher-level users)
* POST http://0.0.0.0:8000/users/api/orgmember/create/ (OrgMember can be created by higher-level users)
* GET http://0.0.0.0:8000/users/api/orgmembers/ (OrgMembers can be seen by higher-level users)
* PUT http://0.0.0.0:8000//users/api/orgmember/<pk>/ ( individual OrgMember can be edited or deleted by a higher-level user)
* POST http://0.0.0.0:8000/users/api/orgadmin/create/ (Same rules as orgmember)
* GET http://0.0.0.0:8000/users/api/orgadmins/ (Same rules as orgmembers)
* PUT http://0.0.0.0:8000//users/api/orgadmin/<pk>/ ( Same rules as orgmember)
* POST http://0.0.0.0:8000/users/api/vtomember/create/ (Same rules as orgmember)
* GET http://0.0.0.0:8000/users/api/vtomembers/ (Same rules as orgmembers)
* PUT http://0.0.0.0:8000//users/api/vtomember/<pk>/ (Same rules as orgmember)

### TO DO:
* Login interface to test if permissions work for each user level. I was only able to test it as a superuser, so each level seems to work for admin level users.
* Endpoints for VTOAdmin. I wasn't too sure about who creates/edits/views/deletes VTOAdmins (superuser??)

2021-05-29 23:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=244) it.</sub>

2021-06-01 05:35 UTC, l2silver commented
@cemgurbey This looks good! But there are a few conflicts. Do you think you could resolve them.

2021-06-01 16:43 UTC, cemgurbey commented
@l2silver Sure thing, I will try to resolve the conflicts tonight!

2021-06-02 03:41 UTC, l2silver commented on data-models/core.drawio
>  <mxfile>
Oh wow you updated the diagram! Excellent

2021-06-02 04:21 UTC, l2silver requested changes
Looking really good so far. Nearly there I think. @Erik-J-D @hkukreja would love to get your opinion

2021-06-02 04:21 UTC, l2silver commented on web-server/users/api/urls.py
> +    path('driver/create/', CreateDriverView.as_view(), name='createdriver'),
I think we might need to change these urls to be more RESTful.

- [ ] Let make everything plural (drivers, orgmembers, orgadmins, etc..)
- [ ] Create calls should be post calls to the root, ie just /drivers (no need for /create)

2021-06-02 04:21 UTC, l2silver commented on web-server/users/api/views.py
> +from rest_framework import status
So do these endpoints all work as expected then?

2021-06-02 04:21 UTC, l2silver commented on web-server/volunteer_toronto_be/urls.py
> +
Can we change these back to /sessions/ , /sessions/refresh/ , /sessions/verify

2021-06-02 04:21 UTC, l2silver commented on web-server/volunteer_toronto_be/urls.py
> +    path('users/api/', include('users.api.urls')),
can we drop the /api/ here.

2021-06-02 22:18 UTC, cemgurbey commented on web-server/users/api/urls.py
> +    path('driver/create/', CreateDriverView.as_view(), name='createdriver'),
Hey! I am currently doing this! So for example, drivers will have:
POST http://0.0.0.0:8000/users/drivers/ (creates a new Driver)
GET http://0.0.0.0:8000/users/api/drivers/ (lists every Driver)
DELETE, GET, PUT, PATCH http://0.0.0.0:8000/users/api/drivers/pk/ (edits **pk**th Driver if the User has the permission, otherwise just display the user)

Should it be like this??

2021-06-02 22:53 UTC, cemgurbey commented on web-server/users/api/views.py
> +from rest_framework import status
They seemed to be. I still couldn't test it thoroughly since I don't know how to log in as OrgMember, OrgAdmin etc. (I only tried the code as Superuser and Anonymous client, and they both look okay)

2021-06-03 00:46 UTC, l2silver approved these changes
Thanks!!!!

2021-06-03 00:46 UTC, l2silver commented on web-server/users/api/urls.py
> +    DriverManageView,
Nice

2021-06-03 00:47 UTC, merged