Feature/241
diglit/volunteer-toronto-volunteer-drivers-app pull request #262
Opened 2021-06-03 02:08 UTC by mefaba

This is a draft request. The reason is I want to be sure that I am heading to right way structurally. For example,
1-Is it okay to use Dialog component for this cards. 
2-Is it okay to use a conditional rendering for DriverFullProfile, RequestPage(component), Backdrop(Loading Component) and SnackBar(success component)

There might be also many typo since I did not fully checked the code.

2021-06-03 02:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=262) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=262) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=262) it.</sub>

2021-06-03 16:46 UTC, l2silver requested changes
So this is pretty close to being done. Definitely on the right path, just need to try to use the react-hook-form library for the request page. Awesome work!

2021-06-03 16:46 UTC, l2silver commented on web-client/src/shared/components/drivers-search/List/DriverCardVT/index.tsx
>  import { Driver } from '../../../../redux/driversSearch/index';
This looks good to me

2021-06-03 16:46 UTC, l2silver commented on web-client/src/shared/components/drivers-search/List/DriverFullProfile/RequestPage/index.tsx
> +import React, { HtmlHTMLAttributes, useState } from 'react';
Ah ok, so here we're look to take advantage of the yup and react-hook-form library that we're using throughout the site. Can you try implementing this page using those libraries. There should be examples in our code base for you to follow.

2021-06-03 18:03 UTC, mefaba commented on web-client/src/shared/components/drivers-search/List/DriverCardVT/index.tsx
>  import { Driver } from '../../../../redux/driversSearch/index';
Thanks

2021-06-03 18:04 UTC, mefaba commented on web-client/src/shared/components/drivers-search/List/DriverFullProfile/RequestPage/index.tsx
> +import React, { HtmlHTMLAttributes, useState } from 'react';
Okay, I will look documentation of yup, react-hook-form and  also I will look implemented pages/components in our repo.

2021-06-12 15:18 UTC, l2silver approved these changes
Excellent work!

2021-06-12 15:55 UTC, l2silver commented
@mefaba  One thing though. Can you fix the travis ci error

2021-06-13 02:12 UTC, WendyChenj approved these changes

2021-06-13 03:01 UTC, mefaba commented
> @mefaba One thing though. Can you fix the travis ci error

fixed travis ci errors

2021-06-13 05:23 UTC, merged