Feature/22
diglit/volunteer-toronto-volunteer-drivers-app pull request #27
Opened 2021-01-17 17:09 UTC by ChrisCottier

Finished creating navigation element of driver registration. Button design do not match design docs, but the functionality is there.

2021-01-17 19:06 UTC, l2silver reviewed
Hey, it looks like there are some lint warnings. I just changed the lint script to throw an error, but in the mean time, can you fix the lint warnings. And I'll try and figure out why netlify was angry.

2021-01-17 19:06 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/CurrentSlide/index.test.tsx
> +    expect(firstNameLabel).toBeInTheDocument;
Awesome!

2021-01-17 19:06 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/CurrentSlide/index.tsx
> +    currentSlide: number
perfect

2021-01-17 19:06 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +import Button from '@material-ui/core/Button';
Perfect

2021-01-17 19:29 UTC, ChrisCottier commented
> Hey, it looks like there are some lint warnings. I just changed the lint script to throw an error, but in the mean time, can you fix the lint warnings. And I'll try and figure out why netlify was angry.

Added return types to React function components. Lint warnings are gone now.

2021-01-18 01:50 UTC, l2silver requested changes
Sorry Chris, 1 more change and we're good.

2021-01-18 01:50 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +            <ButtonGroup size="large">
Perfect use of button group!

2021-01-18 01:50 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/CurrentSlide/index.test.tsx
> +    const { getByText } = render(<CurrentSlide currentSlide={1}/>);
Yes!!! Thank you for testing current slide and not just PersonalInfo.

2021-01-18 15:25 UTC, ChrisCottier commented
> Sorry Chris, 1 more change and we're good.

Sorry I'm not as familiar with GitHub reviews, I couldn't see what / where you wanted changes. Or is it related to the newlines at the end of the files?

2021-01-18 16:55 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +                :<></> }
Do you think you could change instances 
condition ? Component : <></>
to
condition && Component
for when condition is boolean
and condition ? Component : null
when condition has the possibility of being the number 0

2021-01-18 16:56 UTC, l2silver commented
Hey Chris, sorry my comment wasn't recorded. It's this one: https://github.com/diglit/volunteer-toronto-volunteer-drivers-app/pull/27#discussion_r559697576

2021-01-18 19:16 UTC, ChrisCottier commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +                :<></> }
Does that mean just change the React fragments to null instead? Or did you want me to change the turnery logic as well?

2021-01-18 19:24 UTC, ChrisCottier commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +                :<></> }
Just tried it out- changing the fragments to null got rid of the material ui warning.

2021-01-18 21:40 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +                :<></> }
I think that's a good thing, no?

2021-01-18 22:48 UTC, ChrisCottier commented on web-client/src/shared/components/drivers-registration/NavigationButtons/index.tsx
> +                :<></> }
Totally, was just making sure I followed. New commit just pushed to this branch.

2021-01-18 23:58 UTC, l2silver approved these changes

2021-01-19 15:35 UTC, OksanaSam approved these changes
Looks really nice, great job Chris!

2021-01-19 18:41 UTC, WendyChenj approved these changes

2021-01-19 21:30 UTC, merged