#277 added dropdown menu and logout button
diglit/volunteer-toronto-volunteer-drivers-app pull request #285
Opened 2021-06-14 19:26 UTC by mefaba

![image](https://user-images.githubusercontent.com/31761983/121948152-e1752680-cd24-11eb-8408-0e75eafea365.png)

![image](https://user-images.githubusercontent.com/31761983/121948191-ec2fbb80-cd24-11eb-9576-db83e23249a2.png)

2021-06-15 01:10 UTC, l2silver requested changes
This is perfect. Lets just add the true logout logic and finish it.

2021-06-15 01:10 UTC, l2silver commented on web-client/src/shared/components/layout/Header/index.jsx
> +    Promise.resolve().then();
To complete the logout, what we'll do is dispatch an action called "clear" to session reducer . Clear will return the session state to the default state. It will also clear local storage of the session variable. (All of this logic should live inside the action handler). After dispatching this action, send the user back to the login page (/)

2021-06-23 22:12 UTC, mefaba commented
You might want to look change in session/index.ts line 23. I did it because when typescript was not happy with user: null in clear reducer.

2021-06-25 04:04 UTC, l2silver commented on web-client/src/shared/redux/session/index.ts
> +    user: User | null,
So this is causing a lot of typescript issues I take it? That's annoying. Maybe it would be easier to add another property called activeSession to the store, that we toggle true when logged in, and false when logged out

2021-06-25 05:01 UTC, mefaba commented on web-client/src/shared/redux/session/index.ts
> +    user: User | null,
Let me clarify my part of the discussion because I did not full understand your response. On line 54 I am returning a initial state since we want to clean session state. Initial state object is as follows: { loading: true, access: '', refresh: '', user: null }.

At this point typescript complains that user can't be null. To get rid of that I changed line 23 as above.

2021-06-25 12:27 UTC, l2silver commented on web-client/src/shared/redux/session/index.ts
> +    user: User | null,
Oh yeah that's fine. Just make you run npm run test-all to make sure all the tests are passing

2021-06-25 14:42 UTC, mefaba commented on web-client/src/shared/redux/session/index.ts
> +    user: User | null,
Looking it now

2021-06-25 14:47 UTC, mefaba commented on web-client/src/shared/redux/session/index.ts
> +    user: User | null,
It throws some errors related to user being null. It does not throws these errors normally.
![image](https://user-images.githubusercontent.com/31761983/123442189-9f5ca800-d5a2-11eb-8e27-f78d769bd27d.png)

2021-06-25 15:05 UTC, mefaba commented on web-client/src/shared/redux/session/index.ts
> +    user: User | null,
Okay, I believe I came up with a acceptable solution. I just returned initalState variable on clear reducer. So now typescript does not complains. Tests are starting. But not all tests are passing. I believe it is not related to this commit though.

2021-06-25 21:48 UTC, l2silver approved these changes
Awesome!

2021-06-25 21:48 UTC, merged