#24 Create a Sign In Page
diglit/volunteer-toronto-volunteer-drivers-app pull request #32
Opened 2021-01-19 03:14 UTC by ynynl

Enabled inputs for password and username. 
Added links for forget password and apply for driver.
OnSubmit will send a post request
Added minimum styles.

2021-01-19 16:02 UTC, l2silver commented on web-client/src/shared/components/sigin-in-page/SignInPage/SignInPage/index.tsx
> +  const { handleSubmit, register } = useForm<FormData>();
So I think what you've done here is perfect :)

For more complicated forms though, I'd like you to use https://github.com/react-hook-form/resolvers#yup . I'm going to add this to the readme. Just thought I'd make a note

2021-01-19 16:03 UTC, l2silver commented on web-client/src/shared/components/sigin-in-page/SignInPage/SignInPage/index.tsx
> +interface FormData {
great!

2021-01-19 16:03 UTC, l2silver commented on web-client/src/shared/components/sigin-in-page/SignInPage/SignInPage/index.tsx
> +      if (response.ok) {
haha, great

2021-01-19 22:40 UTC, ynynl commented on web-client/src/shared/components/sigin-in-page/SignInPage/SignInPage/index.tsx
> +import React from 'react';
Thank you for pointing this out! I have changed it

2021-01-19 22:42 UTC, ynynl commented on web-client/src/shared/components/sigin-in-page/SignInPage/SignInPage/index.tsx
> +  const { handleSubmit, register } = useForm<FormData>();
Thanks! I will look that up.

2021-01-21 00:47 UTC, l2silver requested changes

2021-01-21 00:47 UTC, l2silver commented on web-client/src/pages/signin.tsx
> +import SignInPage from "../shared/components/SignInPage";
Am I crazy, or is the SignInPage missing from this pull request now?

2021-01-21 00:54 UTC, ynynl commented on web-client/src/pages/signin.tsx
> +import SignInPage from "../shared/components/SignInPage";
I have no idea why this happens. let me try to do another push.

2021-01-21 01:07 UTC, ynynl commented on web-client/src/pages/signin.tsx
> +import SignInPage from "../shared/components/SignInPage";
Okay the file is back now.

2021-01-21 02:38 UTC, l2silver requested changes
Almost there, just a couple small things.

2021-01-21 02:38 UTC, l2silver commented on web-client/src/shared/components/SignInPage/SignInPage.module.scss
> +.header {
last thing (hopefully). Do you mind changing the name of this file to index.module.scss

Thanks.

2021-01-21 02:38 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +                  fullWidth
I think if you have a label, you also need to include an id prop. Do you think you could add that?

2021-01-21 02:38 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +                  label="Password"
Likewise for the id here aswell

2021-01-21 18:07 UTC, ynynl commented on web-client/src/shared/components/SignInPage/index.tsx
> +                  label="Password"
like 'id =passeword' in the textfield tag?

2021-01-21 18:07 UTC, ynynl commented on web-client/src/shared/components/SignInPage/SignInPage.module.scss
> +.header {
np!

2021-01-21 23:58 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +                  label="Password"
yep

2021-01-21 23:59 UTC, l2silver commented on web-client/src/shared/components/SignInPage/index.tsx
> +                  fullWidth
https://www.w3schools.com/tags/att_label_for.asp . This is important for accessibility purposes, as people with screen readers will have more information about the input

2021-01-22 03:38 UTC, ynynl commented on web-client/src/shared/components/SignInPage/index.tsx
> +                  fullWidth
Thank you! I have made the changes you suggested.

2021-02-03 02:09 UTC, l2silver approved these changes

2021-02-17 01:55 UTC, merged