#4 -  Added Swagger
diglit/volunteer-toronto-volunteer-drivers-app pull request #38
Opened 2021-01-21 20:14 UTC by andreipakemp

2021-01-21 20:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=38) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=38) it.</sub>

2021-01-21 22:14 UTC, Erik-J-D requested changes

2021-01-21 22:14 UTC, Erik-J-D commented on web-server/volunteer_toronto_be/urls.py
> +        description="Test description",
Can you change this description to a quick sentence about what this app does?

2021-01-21 22:14 UTC, Erik-J-D commented on web-server/volunteer_toronto_be/urls.py
> +        license=openapi.License(name="BSD License"),
The ToS, contact info, and license all need to be updated - @l2silver can you chime in on what to fill in here?

2021-01-21 22:26 UTC, Erik-J-D commented
@andreipakemp If you could also add a note to the README describing how to access the swagger that would be great.

2021-01-30 15:22 UTC, Erik-J-D commented on README.md
> -# Volunteer Drivers App
Please don't delete the README. Can you add the instructions to the web-server README instead of the root one?

2021-01-30 16:18 UTC, l2silver commented on web-server/volunteer_toronto_be/urls.py
> +        license=openapi.License(name="BSD License"),
We don't have a terms of service yet, we'll need to write something there. Contact can be info@diglit.ca . License is (SAP Individual Contributor License Agreement), https://gist.github.com/CLAassistant/bd1ea8ec8aa0357414e8

2021-02-14 15:23 UTC, Erik-J-D approved these changes

2021-02-14 15:24 UTC, Erik-J-D approved these changes

2021-02-14 15:24 UTC, merged