WIP: Feature/66 Create E2E pretest for personal info section of signup
diglit/volunteer-toronto-volunteer-drivers-app pull request #70
Opened 2021-03-19 23:55 UTC by Haris188

2021-03-19 23:57 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +const mockDriverInputData = {
Haha, this is also my default test info!

2021-03-19 23:59 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +const mockDriverInputData = {
So, to keeps things consistent, @WendyChenj created a factory method to create drivers. Do you think you could use that. It uses the fishery library. Message her for details on slack if you're confused.

2021-03-20 00:00 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +
This is great

2021-03-20 00:01 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +            expect(errorMsgElem).toBeInTheDocument()
Perhaps a more concise way of doing this is using the findByText method, which should throw an error if the elem does not exist.

2021-03-20 00:02 UTC, l2silver commented on web-client/package.json
> +    "next": "^10.0.9",
Any reason why you changed the next version here?

2021-03-20 00:04 UTC, l2silver reviewed
Wow Harris! This is fantastic. Thank you so much for doing this. Just a few comments.

2021-03-20 00:04 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.tsx
> +const PersonalInfo = (props:any): React.ReactElement => {
We try to avoid using the any type. Can you change this to be more descriptive.

2021-03-20 00:07 UTC, Haris188 commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +const mockDriverInputData = {
Yes...got that info straight from "The Office". Just finished the series lol.

Yes I can certainly revert to the DriverFactory. I will do that on next commit but I might have to change it because the object it returns are missing some properties like PhoneNumber and LastName.

2021-03-20 00:08 UTC, Haris188 commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +
Thanks!

2021-03-20 00:09 UTC, Haris188 commented on web-client/package.json
> +    "next": "^10.0.9",
I did not do it deliberately, I only installed UserEvent from testing. Should I revert it back?

2021-03-20 00:10 UTC, Haris188 commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.tsx
> +const PersonalInfo = (props:any): React.ReactElement => {
Certainly

2021-03-20 19:50 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +const mockDriverInputData = {
I think the nice thing about that library is it should work with values you add to it, so you might need to modify it.

2021-03-20 19:51 UTC, l2silver commented on web-client/package.json
> +    "next": "^10.0.9",
No it should be fine. I just didn't realize a library could change the version like that

2021-03-20 20:38 UTC, Haris188 commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +const mockDriverInputData = {
I took a look at DriverFactory and it depends on Driver interface. Adding custom properties is seeming a little hacky. I feel like we can create an interface for the PersonalInfo form values and create a separate factory which depends on that interface. It will work same as DriverFactory but will have a separate interface for data types. What do you think?

2021-03-21 00:19 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PersonalInfo/index.test.tsx
> +const mockDriverInputData = {
Ah, in that case, go for it!

2021-03-22 03:20 UTC, l2silver commented on e2e/cypress/integration/driverRegistration/personalInfo.spec.js
> +const inputLabels = {
Very interesting!

2021-03-22 03:23 UTC, l2silver commented on e2e/cypress/integration/driverRegistration/personalInfo.spec.js
> +    const populateFieldsWithValidData = ()=>{
Feels like this should also include a cy.visit ?

2021-03-22 03:25 UTC, l2silver requested changes
Amazing work! I love have concise everything is. I think the only thing that needs to be done is to add cy.visit to the cypress tests so the user is on the right page when they make those assumptions.

2021-03-22 04:17 UTC, Haris188 commented on e2e/cypress/integration/driverRegistration/personalInfo.spec.js
> +    const populateFieldsWithValidData = ()=>{
added :)

2021-03-23 00:10 UTC, l2silver commented
Hey @Haris188 just need to fix merge conflcits, and make sure travis ci check passes.

2021-03-23 04:48 UTC, Haris188 commented
Hey @l2silver 

Travis CI tests are failing because presets are failing. I have resolved the merging conflicts.

2021-03-24 01:44 UTC, l2silver commented
Hey @Haris188 , @ynynl finished the personal info section. Do you think you could change this ticket to get the tests running properly. Also, it looks like she wrote for own react tests, so we might have to take out someones depending on which makes more sense, I'll leave that up to you to decide.

2021-03-24 01:50 UTC, ynynl commented
Hi @l2silver, the test is not written by me. I think it's Chris wrote the test.  I am okay with any approach.

2021-03-24 02:32 UTC, Haris188 commented
Hey @l2silver, @ynynl 

I have taken a look at the tests. The test that I have written are more user action oriented and they also check the validity of the data as well although, I am missing a couple of test cases that are present the other test suite.

I am thinking of using my tests but because they cover the other test suits and I can add missing couple of tests to my tests suite as well. What do you think?

2021-03-25 18:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=70) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=70) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Haris188<br/>:x: Haris Ahmad<br/><hr/>**Haris Ahmad** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/diglit/volunteer-toronto-volunteer-drivers-app?pullRequest=70) it.</sub>

2021-03-27 04:02 UTC, Haris188 commented
Hey @l2silver ,

I have accidentally committed with a wrong email. Now its asking me to accept license. I accepted that but its still not merging. What should I do?

2021-03-27 12:35 UTC, l2silver commented
> Hey @l2silver ,
> 
> I have accidentally committed with a wrong email. Now its asking me to accept license. I accepted that but its still not merging. What should I do?

Don't worry about it! I'll just have to merge it when its approved. The same thing happened to me too

2021-03-27 20:04 UTC, l2silver commented
Hey @Haris188 , I updated develop so that travis ci fires off the cypress tests. Lets see if everything is working smoothly.

2021-03-27 22:38 UTC, l2silver commented
Amazing!

2021-03-27 22:38 UTC, closed without merging