WIP - #67 Create Review Section for registration page
diglit/volunteer-toronto-volunteer-drivers-app pull request #79
Opened 2021-03-30 02:02 UTC by WendyChenj

Completed:

- Create Review Section

Todo:

- Test

2021-03-30 03:14 UTC, WendyChenj commented
Hey @l2silver, I've done a manual test for our registration page. Basically, we've finished most of the functions for the registration process. Here are some features we may need to work on in the near future:

- Save information for each registration page using the 'Next' button. Currently, we use the 'save' button for each section to update the registration information in the redux file.

- For the 'Your Needs' section, the map is missing for lack of geographical data.

- For the 'Pre-Requirements' section, if a user chooses 'completed a police records check in the last 6/ 12 months' or 'completed a driving abstract in the last 6/ 12 months' option, there will be a date selector for users to choose when they completed the check. We may need to add a date validation for this selection as we can choose future dates such as 2023-03-01 even though the option says 'in the last 6/ 12 months'.

- For the 'signature' in the Agreement section, I'm not sure if this signature here should keep consistent with the user's first name and last name which are filled in the Personal Info section.

Thank you :)

2021-04-02 00:57 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/PreScreenRequirements/label.ts
> +    'I have a clear driving abstract completed within the last 6 months',
Thank you for finding this!

2021-04-02 01:07 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/Review/index.tsx
> +    Sunday: availableDates.filter(ele => ele.date === 'Sunday')[0].availableTimes.includes(time),
A bit more idiosyncratic would be [].find() instead of filter()[0]

2021-04-02 01:08 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/Review/index.tsx
> +  const availableDatesAndTimes = [...TIMES.map( time => ({
I don't think you need [...TIMES.map , you can just do TIMES.map because it returns a new array

2021-04-02 01:09 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/Review/index.tsx
> +  const checkedLicenseAndVehicles = [...licenses.map(license => {
https://github.com/diglit/volunteer-toronto-volunteer-drivers-app/pull/79/files#r606023300

2021-04-02 01:09 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/Review/index.tsx
> +  const checkedAgreements = [...agreements.map(agreement => {
https://github.com/diglit/volunteer-toronto-volunteer-drivers-app/pull/79/files#r606023300

2021-04-02 01:10 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/Review/index.tsx
> +      label: LicenseAndVehicleLabel.filter(label => label.name === license)[0].label
You can use find here as well

2021-04-02 01:10 UTC, l2silver commented on web-client/src/shared/components/drivers-registration/Review/index.tsx
> +      label: agreementLabel.filter(label => label.name === agreement)[0].label
You can use find here also

2021-04-02 01:13 UTC, l2silver requested changes
Looks really good. Just a few changes for slightly more idiosyncratic coding in javascript, but functionally it's the same.

2021-04-21 01:01 UTC, l2silver approved these changes
Yes!!! Thank you @WendyChenj !

2021-04-21 01:02 UTC, merged